#!/usr/bin/env python3
"""
REDOPS Report Generator
Reads wiki/ and generates professional reports for each mode.
Usage: python3 tools/report.py [pentest|redteam|bugbounty|poc] [options]
"""

import json
import sys
import os
import re
from pathlib import Path
from datetime import datetime

BASE = Path(__file__).parent.parent
WIKI = BASE / "wiki"
STATE_FILE = BASE / "state" / "session.json"
OUTPUT = BASE / "wiki" / "reports"
OUTPUT.mkdir(parents=True, exist_ok=True)

def load_state():
    with open(STATE_FILE) as f:
        return json.load(f)

def get_timestamp():
    return datetime.now().strftime("%Y-%m-%d %H:%M")

def generate_pentest_report(state):
    """PTES-format penetration test report"""
    ts = get_timestamp()
    engagement = state.get('engagement', {})
    findings = state.get('findings', {})
    
    vulns = findings.get('vulnerabilities', [])
    critical = [v for v in vulns if v.get('severity') == 'Critical']
    high = [v for v in vulns if v.get('severity') == 'High']
    medium = [v for v in vulns if v.get('severity') == 'Medium']
    low = [v for v in vulns if v.get('severity') == 'Low']
    
    report = f"""# Penetration Test Report
## {engagement.get('name', 'Unknown Engagement')}

---

**Classification:** CONFIDENTIAL  
**Client:** {engagement.get('client', 'TBD')}  
**Date:** {ts}  
**Tester:** SPECTRE (REDOPS Agent)  
**Engagement Type:** External/Internal Penetration Test  
**Authorization:** {engagement.get('authorization', 'See SOW')}  

---

## Executive Summary

This report presents the findings from a penetration test conducted against
{engagement.get('client', 'the client')}'s environment. The assessment identified
**{len(vulns)} vulnerabilities** across tested systems.

| Severity | Count |
|----------|-------|
| Critical | {len(critical)} |
| High     | {len(high)} |
| Medium   | {len(medium)} |
| Low      | {len(low)} |

### Risk Rating: {'CRITICAL' if critical else 'HIGH' if high else 'MEDIUM' if medium else 'LOW'}

---

## Scope

| Asset | Type | Status |
|-------|------|--------|
"""
    
    # Add targets
    for t in state.get('targets', [state.get('active_target', 'N/A')]):
        report += f"| {t} | IP/Domain | Tested |\n"
    
    report += f"""
---

## Findings

"""
    
    # Group by severity
    all_vulns = critical + high + medium + low
    for i, vuln in enumerate(all_vulns, 1):
        report += f"""### Finding {i}: {vuln.get('name', 'Unknown')}

**Severity:** {vuln.get('severity', 'Unknown')}  
**Service/Asset:** {vuln.get('service', 'Unknown')}  
**CVSS Score:** {vuln.get('cvss', 'TBD')}  

**Description:**  
{vuln.get('description', 'See wiki/findings/ for details.')}

**Evidence:**  
{vuln.get('evidence', 'See raw/ directory for tool output.')}

**Remediation:**  
{vuln.get('remediation', 'Apply vendor patches and follow hardening guidelines.')}

---

"""
    
    report += f"""## Recommendations

1. Prioritize remediation of Critical and High findings immediately
2. Schedule Medium findings for next patch cycle
3. Review Low findings as part of security hardening program
4. Conduct follow-up assessment after remediation

## Methodology

This assessment followed the Penetration Testing Execution Standard (PTES):
1. Pre-engagement Interactions
2. Intelligence Gathering
3. Threat Modeling
4. Vulnerability Analysis
5. Exploitation
6. Post Exploitation
7. Reporting

## Tools Used

| Tool | Purpose |
|------|---------|
| Nmap | Network scanning |
| Gobuster/Feroxbuster | Directory enumeration |
| Metasploit | Exploitation framework |
| Nikto | Web vulnerability scanning |
| SQLMap | SQL injection testing |
| Hydra | Credential testing |
| LinPEAS/WinPEAS | Post-exploitation enumeration |

---

*Report generated by REDOPS Agent. Review and validate all findings before delivery.*
*Generated: {ts}*
"""
    return report


def generate_bugbounty_poc(args):
    """Bug bounty PoC template"""
    ts = get_timestamp()
    
    vuln_type = getattr(args, 'type', 'IDOR')
    severity = getattr(args, 'severity', 'High')
    asset = getattr(args, 'asset', 'https://target.com/endpoint')
    
    # CVSS mapping
    cvss_map = {'Critical': '9.0-10.0', 'High': '7.0-8.9', 'Medium': '4.0-6.9', 'Low': '0.1-3.9'}
    bounty_map = {
        'Critical': '$5,000–$50,000+',
        'High': '$1,000–$10,000',
        'Medium': '$200–$2,000',
        'Low': '$50–$500'
    }
    
    poc = f"""# Bug Report: {vuln_type}

**Program:** [Program Name]  
**Submitted:** {ts}  
**Severity:** {severity}  
**CVSS 3.1:** {cvss_map.get(severity, '7.5')}  
**CWE:** [CWE-XXX — CWE Name]  
**Bounty Estimate:** {bounty_map.get(severity, 'TBD')}  
**Asset:** {asset}  

---

## Summary

[2-3 sentences: what is the bug, where, what can an attacker do]

Example: An Insecure Direct Object Reference (IDOR) vulnerability in the profile
endpoint allows an authenticated attacker to access or modify any user's private
data by manipulating the `user_id` parameter.

---

## Impact

[Concrete business impact. What data? Which users? What operations?]

An attacker with a valid account can:
1. Read private profile data of any user (name, email, address, payment info)
2. Modify any user's account settings
3. This affects all N registered users

---

## Steps to Reproduce

**Setup:**
- Account A (attacker): attacker@email.com
- Account B (victim): victim@email.com (use your own test account)

**Steps:**
1. Log in as Account A
2. Navigate to `{asset}`
3. Intercept the request in Burp Suite
4. Modify `user_id=YOUR_ID` to `user_id=VICTIM_ID`
5. Forward the request
6. Observe: response contains Account B's private data

---

## Proof of Concept

### Request
```http
GET /api/v1/user/VICTIM_ID/profile HTTP/1.1
Host: target.com
Authorization: Bearer [ATTACKER_JWT_TOKEN]
```

### Response
```json
{{
  "id": "VICTIM_ID",
  "email": "victim@email.com",
  "private_field": "sensitive_data_here"
}}
```

### Screenshot
[Attach sanitized screenshot — blur real PII]

---

## Root Cause

The server does not validate that the authenticated user is authorized to
access the requested user ID. Authorization check is missing in:
`[endpoint/function if known]`

---

## Remediation

1. Implement server-side authorization: verify the authenticated user owns the
   requested resource before returning data
2. Use indirect object references (map user-visible IDs to internal ones)
3. Add automated tests for IDOR in CI/CD pipeline

---

## Timeline

| Date | Event |
|------|-------|
| {ts} | Vulnerability discovered |
| {ts} | PoC confirmed (3x reproduction) |
| {ts} | Report submitted |

---

## Additional Notes

- Bug was reproduced on production using only test accounts I control
- No real user data was accessed or stored
- Tested on: Chrome 120, Firefox 121

---

*Filed to: wiki/bounties/[SUBMISSION_ID].md*
"""
    return poc


def generate_redteam_report(state):
    """Executive + Technical red team report"""
    ts = get_timestamp()
    engagement = state.get('engagement', {})
    rt = state.get('red_team', {})
    findings = state.get('findings', {})
    
    ttps = findings.get('ttps_executed', [])
    objectives = rt.get('objectives', [])
    lateral = rt.get('lateral_hosts', [])
    
    report = f"""# Red Team Assessment Report

## {engagement.get('name', 'Unknown Engagement')}

---

**Classification:** STRICTLY CONFIDENTIAL  
**Client:** {engagement.get('client', 'TBD')}  
**Assessment Type:** Full-Scope Adversary Simulation  
**Date:** {ts}  
**Team:** WRAITH (REDOPS Agent)  

---

## Executive Summary

### Objectives

| Objective | Status | Notes |
|-----------|--------|-------|
"""
    
    for obj in objectives:
        status = "✓ ACHIEVED" if obj.get('achieved') else "✗ NOT ACHIEVED"
        report += f"| {obj.get('name', 'TBD')} | {status} | {obj.get('notes', '')} |\n"
    
    report += f"""
### Attack Timeline

[Timeline visualization would go here — see wiki/sessions/ for detailed log]

---

## Attack Narrative

### Initial Access

[Describe how initial access was obtained — phishing, external service, credential stuffing]

### Lateral Movement

Systems compromised: {len(lateral)}

| Host | Method | Credentials Used |
|------|--------|-----------------|
"""
    
    for host in lateral:
        report += f"| {host.get('ip', 'N/A')} | {host.get('method', 'N/A')} | {host.get('creds', 'N/A')} |\n"
    
    report += f"""
---

## MITRE ATT&CK Coverage

| Tactic | Technique | ID | Success |
|--------|-----------|-----|---------|
"""
    
    for ttp in ttps:
        status = "✓" if ttp.get('result') == 'SUCCESS' else "✗"
        report += f"| {ttp.get('tactic', '')} | {ttp.get('name', '')} | {ttp.get('id', '')} | {status} |\n"
    
    report += f"""
---

## Detection Analysis

### Detected Behaviors

[List what the blue team caught]

### Undetected Behaviors

[List what evaded detection — these are the gaps]

### MTTD (Mean Time to Detect)

- Initial compromise: [X hours/days after breach]
- Lateral movement detected: [Y hours after start]
- Escalation triggered: [Z hours]

---

## Recommendations

### Immediate Actions (0-30 days)
1. [Specific detection rule for undetected technique]
2. [Credential hygiene — where harvested creds came from]

### Short-term (30-90 days)
1. [EDR tuning based on missed detections]
2. [Network segmentation gaps]

### Strategic (90+ days)
1. [Purple team exercises to validate detections]
2. [Incident response playbook updates]

---

## Remediation Roadmap

[Prioritized list based on attack path criticality]

---

*Generated by WRAITH / REDOPS Agent. For authorized personnel only.*  
*{ts}*
"""
    return report


def main():
    if len(sys.argv) < 2:
        print("Usage: report.py [pentest|redteam|bugbounty|poc] [options]")
        sys.exit(1)
    
    mode = sys.argv[1]
    state = load_state()
    ts_file = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    if mode == 'pentest':
        content = generate_pentest_report(state)
        filename = OUTPUT / f"pentest_report_{ts_file}.md"
    elif mode == 'redteam':
        content = generate_redteam_report(state)
        filename = OUTPUT / f"redteam_report_{ts_file}.md"
    elif mode in ['bugbounty', 'poc']:
        class Args:
            pass
        args = Args()
        args.type = sys.argv[2] if len(sys.argv) > 2 else 'Vulnerability'
        args.severity = sys.argv[3] if len(sys.argv) > 3 else 'High'
        args.asset = sys.argv[4] if len(sys.argv) > 4 else 'https://target.com'
        content = generate_bugbounty_poc(args)
        filename = OUTPUT / f"poc_{ts_file}.md"
    else:
        print(f"Unknown mode: {mode}")
        sys.exit(1)
    
    with open(filename, 'w') as f:
        f.write(content)
    
    print(f"[✓] Report generated: {filename}")
    print(f"    Word count: ~{len(content.split())}")
    
    # Log to wiki
    log_ts = get_timestamp()
    with open(BASE / "wiki" / "log.md", 'a') as f:
        f.write(f"\n## [{log_ts}] report | Generated {mode} report: {filename.name}\n")

if __name__ == '__main__':
    main()
